-- VICCOM - Migracion incremental de categorias jerarquicas para CT Connect
-- Objetivo:
--   - No elimina tablas ni datos.
--   - Mantiene products.categoria_id y las consultas actuales.
--   - Agrega parent_id/nivel/path/ct_key para arbol de categorias.
--   - Incluye bloque de rollback al final, comentado.

BEGIN;

-- 1. Columnas jerarquicas. Todas son incrementales y compatibles.
ALTER TABLE categories
  ADD COLUMN IF NOT EXISTS parent_id UUID REFERENCES categories(id) ON DELETE SET NULL;

  ALTER TABLE categories
    ADD COLUMN IF NOT EXISTS nivel INTEGER NOT NULL DEFAULT 0;

    ALTER TABLE categories
      ADD COLUMN IF NOT EXISTS path TEXT;

      ALTER TABLE categories
        ADD COLUMN IF NOT EXISTS ct_key TEXT;

        ALTER TABLE categories
          ADD COLUMN IF NOT EXISTS ct_parent_key TEXT;

          -- 2. Datos actuales: las categorias existentes quedan como categorias raiz.
          UPDATE categories
          SET
            parent_id = NULL,
              nivel = 0,
                path = COALESCE(NULLIF(path, ''), slug),
                  ct_key = COALESCE(NULLIF(ct_key, ''), slug)
                  WHERE parent_id IS NULL;

                  -- 3. Indices para consultas jerarquicas y futuras importaciones CT.
                  CREATE INDEX IF NOT EXISTS idx_categories_parent_id
                    ON categories(parent_id);

                    CREATE INDEX IF NOT EXISTS idx_categories_nivel
                      ON categories(nivel);

                      CREATE INDEX IF NOT EXISTS idx_categories_path
                        ON categories(path);

                        CREATE INDEX IF NOT EXISTS idx_categories_ct_key
                          ON categories(ct_key);

                          CREATE INDEX IF NOT EXISTS idx_categories_activo_parent_orden
                            ON categories(activo, parent_id, orden);

                            -- 4. Unicidad por rama sin romper el indice UNIQUE existente de slug.
                            -- Nota: el schema actual ya tiene categories.slug UNIQUE global. Estos indices
                            -- preparan el modelo por rama para una futura relajacion controlada del UNIQUE
                            -- global, si CT permite slugs repetidos en ramas distintas.
                            CREATE UNIQUE INDEX IF NOT EXISTS idx_categories_root_slug_unique
                              ON categories(slug)
                                WHERE parent_id IS NULL;

                                CREATE UNIQUE INDEX IF NOT EXISTS idx_categories_parent_slug_unique
                                  ON categories(parent_id, slug)
                                    WHERE parent_id IS NOT NULL;

                                    -- 5. Evitar ciclos directos.
                                    DO $$
                                    BEGIN
                                      IF NOT EXISTS (
                                          SELECT 1
                                              FROM pg_constraint
                                                  WHERE conname = 'chk_categories_parent_not_self'
                                                        AND conrelid = 'categories'::regclass
                                                          ) THEN
                                                              ALTER TABLE categories
                                                                    ADD CONSTRAINT chk_categories_parent_not_self
                                                                          CHECK (parent_id IS NULL OR parent_id <> id);
                                                                            END IF;
                                                                            END $$;

                                                                            -- 6. Funcion para recalcular path y nivel de todo el arbol.
                                                                            CREATE OR REPLACE FUNCTION refresh_category_paths()
                                                                            RETURNS VOID AS $$
                                                                            BEGIN
                                                                              WITH RECURSIVE category_tree AS (
                                                                                  SELECT
                                                                                        id,
                                                                                              slug,
                                                                                                    parent_id,
                                                                                                          0 AS computed_nivel,
                                                                                                                slug::TEXT AS computed_path
                                                                                                                    FROM categories
                                                                                                                        WHERE parent_id IS NULL

                                                                                                                            UNION ALL

                                                                                                                                SELECT
                                                                                                                                      child.id,
                                                                                                                                            child.slug,
                                                                                                                                                  child.parent_id,
                                                                                                                                                        parent.computed_nivel + 1,
                                                                                                                                                              parent.computed_path || '/' || child.slug
                                                                                                                                                                  FROM categories child
                                                                                                                                                                      INNER JOIN category_tree parent ON child.parent_id = parent.id
                                                                                                                                                                        )
                                                                                                                                                                          UPDATE categories c
                                                                                                                                                                            SET
                                                                                                                                                                                nivel = category_tree.computed_nivel,
                                                                                                                                                                                    path = category_tree.computed_path,
                                                                                                                                                                                        updated_at = NOW()
                                                                                                                                                                                          FROM category_tree
                                                                                                                                                                                            WHERE c.id = category_tree.id;
                                                                                                                                                                                            END;
                                                                                                                                                                                            $$ LANGUAGE plpgsql;

                                                                                                                                                                                            -- 7. Funcion para obtener una categoria y todos sus descendientes.
                                                                                                                                                                                            CREATE OR REPLACE FUNCTION get_category_descendants(p_category_id UUID)
                                                                                                                                                                                            RETURNS TABLE(id UUID) AS $$
                                                                                                                                                                                            BEGIN
                                                                                                                                                                                              RETURN QUERY
                                                                                                                                                                                                WITH RECURSIVE category_tree AS (
                                                                                                                                                                                                    SELECT c.id
                                                                                                                                                                                                        FROM categories c
                                                                                                                                                                                                            WHERE c.id = p_category_id

                                                                                                                                                                                                                UNION ALL

                                                                                                                                                                                                                    SELECT child.id
                                                                                                                                                                                                                        FROM categories child
                                                                                                                                                                                                                            INNER JOIN category_tree parent ON child.parent_id = parent.id
                                                                                                                                                                                                                                WHERE child.activo = TRUE
                                                                                                                                                                                                                                  )
                                                                                                                                                                                                                                    SELECT category_tree.id FROM category_tree;
                                                                                                                                                                                                                                    END;
                                                                                                                                                                                                                                    $$ LANGUAGE plpgsql STABLE;

                                                                                                                                                                                                                                    -- 8. Funcion para resolver categoria por path de slugs.
                                                                                                                                                                                                                                    CREATE OR REPLACE FUNCTION get_category_by_path(p_path TEXT)
                                                                                                                                                                                                                                    RETURNS TABLE(
                                                                                                                                                                                                                                      id UUID,
                                                                                                                                                                                                                                        nombre TEXT,
                                                                                                                                                                                                                                          slug TEXT,
                                                                                                                                                                                                                                            parent_id UUID,
                                                                                                                                                                                                                                              nivel INTEGER,
                                                                                                                                                                                                                                                path TEXT
                                                                                                                                                                                                                                                ) AS $$
                                                                                                                                                                                                                                                BEGIN
                                                                                                                                                                                                                                                  RETURN QUERY
                                                                                                                                                                                                                                                    SELECT c.id, c.nombre, c.slug, c.parent_id, c.nivel, c.path
                                                                                                                                                                                                                                                      FROM categories c
                                                                                                                                                                                                                                                        WHERE c.path = trim(both '/' from p_path)
                                                                                                                                                                                                                                                            AND c.activo = TRUE
                                                                                                                                                                                                                                                              LIMIT 1;
                                                                                                                                                                                                                                                              END;
                                                                                                                                                                                                                                                              $$ LANGUAGE plpgsql STABLE;

                                                                                                                                                                                                                                                              -- 9. Aplicar path inicial.
                                                                                                                                                                                                                                                              SELECT refresh_category_paths();

                                                                                                                                                                                                                                                              -- 10. Vista de catalogo compatible: mantiene campos previos y agrega metadata jerarquica.
                                                                                                                                                                                                                                                              CREATE OR REPLACE VIEW v_products_catalog AS
                                                                                                                                                                                                                                                              SELECT
                                                                                                                                                                                                                                                                p.id,
                                                                                                                                                                                                                                                                  p.sku_ct,
                                                                                                                                                                                                                                                                    p.nombre,
                                                                                                                                                                                                                                                                      p.slug,
                                                                                                                                                                                                                                                                        p.descripcion,
                                                                                                                                                                                                                                                                          p.subcategoria,
                                                                                                                                                                                                                                                                            p.costo_ct,
                                                                                                                                                                                                                                                                              p.precio_publico,
                                                                                                                                                                                                                                                                                p.precio_antes,
                                                                                                                                                                                                                                                                                  p.margen_aplicado,
                                                                                                                                                                                                                                                                                    p.existencia_total,
                                                                                                                                                                                                                                                                                      p.imagen_principal,
                                                                                                                                                                                                                                                                                        p.activo,
                                                                                                                                                                                                                                                                                          p.destacado,
                                                                                                                                                                                                                                                                                            p.en_oferta,
                                                                                                                                                                                                                                                                                              p.fecha_fin_oferta,
                                                                                                                                                                                                                                                                                                p.fecha_actualizacion,
                                                                                                                                                                                                                                                                                                  b.id        AS marca_id,
                                                                                                                                                                                                                                                                                                    b.nombre    AS marca_nombre,
                                                                                                                                                                                                                                                                                                      b.slug      AS marca_slug,
                                                                                                                                                                                                                                                                                                        b.logo_url  AS marca_logo,
                                                                                                                                                                                                                                                                                                          c.id        AS categoria_id,
                                                                                                                                                                                                                                                                                                            c.nombre    AS categoria_nombre,
                                                                                                                                                                                                                                                                                                              c.slug      AS categoria_slug,
                                                                                                                                                                                                                                                                                                                c.parent_id AS categoria_parent_id,
                                                                                                                                                                                                                                                                                                                  c.nivel     AS categoria_nivel,
                                                                                                                                                                                                                                                                                                                    c.path      AS categoria_path,
                                                                                                                                                                                                                                                                                                                      COALESCE(tgz.existencia, 0) AS existencia_tuxtla
                                                                                                                                                                                                                                                                                                                      FROM products p
                                                                                                                                                                                                                                                                                                                      LEFT JOIN brands     b ON p.marca_id = b.id
                                                                                                                                                                                                                                                                                                                      LEFT JOIN categories c ON p.categoria_id = c.id
                                                                                                                                                                                                                                                                                                                      LEFT JOIN inventory  tgz ON tgz.product_id = p.id AND tgz.almacen = 'TGZ'
                                                                                                                                                                                                                                                                                                                      WHERE p.activo = TRUE
                                                                                                                                                                                                                                                                                                                        AND p.descontinuado = FALSE;

                                                                                                                                                                                                                                                                                                                        COMMIT;

                                                                                                                                                                                                                                                                                                                        -- ROLLBACK MANUAL, si se necesitara revertir esta capa jerarquica.
                                                                                                                                                                                                                                                                                                                        -- Ejecutar como script separado, no junto con la migracion de arriba.
                                                                                                                                                                                                                                                                                                                        --
                                                                                                                                                                                                                                                                                                                        -- BEGIN;
                                                                                                                                                                                                                                                                                                                        --
                                                                                                                                                                                                                                                                                                                        -- CREATE OR REPLACE VIEW v_products_catalog AS
                                                                                                                                                                                                                                                                                                                        -- SELECT
                                                                                                                                                                                                                                                                                                                        --   p.id,
                                                                                                                                                                                                                                                                                                                        --   p.sku_ct,
                                                                                                                                                                                                                                                                                                                        --   p.nombre,
                                                                                                                                                                                                                                                                                                                        --   p.slug,
                                                                                                                                                                                                                                                                                                                        --   p.descripcion,
                                                                                                                                                                                                                                                                                                                        --   p.subcategoria,
                                                                                                                                                                                                                                                                                                                        --   p.costo_ct,
                                                                                                                                                                                                                                                                                                                        --   p.precio_publico,
                                                                                                                                                                                                                                                                                                                        --   p.precio_antes,
                                                                                                                                                                                                                                                                                                                        --   p.margen_aplicado,
                                                                                                                                                                                                                                                                                                                        --   p.existencia_total,
                                                                                                                                                                                                                                                                                                                        --   p.imagen_principal,
                                                                                                                                                                                                                                                                                                                        --   p.activo,
                                                                                                                                                                                                                                                                                                                        --   p.destacado,
                                                                                                                                                                                                                                                                                                                        --   p.en_oferta,
                                                                                                                                                                                                                                                                                                                        --   p.fecha_fin_oferta,
                                                                                                                                                                                                                                                                                                                        --   p.fecha_actualizacion,
                                                                                                                                                                                                                                                                                                                        --   b.id        AS marca_id,
                                                                                                                                                                                                                                                                                                                        --   b.nombre    AS marca_nombre,
                                                                                                                                                                                                                                                                                                                        --   b.slug      AS marca_slug,
                                                                                                                                                                                                                                                                                                                        --   b.logo_url  AS marca_logo,
                                                                                                                                                                                                                                                                                                                        --   c.id        AS categoria_id,
                                                                                                                                                                                                                                                                                                                        --   c.nombre    AS categoria_nombre,
                                                                                                                                                                                                                                                                                                                        --   c.slug      AS categoria_slug,
                                                                                                                                                                                                                                                                                                                        --   COALESCE(tgz.existencia, 0) AS existencia_tuxtla
                                                                                                                                                                                                                                                                                                                        -- FROM products p
                                                                                                                                                                                                                                                                                                                        -- LEFT JOIN brands     b ON p.marca_id = b.id
                                                                                                                                                                                                                                                                                                                        -- LEFT JOIN categories c ON p.categoria_id = c.id
                                                                                                                                                                                                                                                                                                                        -- LEFT JOIN inventory  tgz ON tgz.product_id = p.id AND tgz.almacen = 'TGZ'
                                                                                                                                                                                                                                                                                                                        -- WHERE p.activo = TRUE
                                                                                                                                                                                                                                                                                                                        --   AND p.descontinuado = FALSE;
                                                                                                                                                                                                                                                                                                                        --
                                                                                                                                                                                                                                                                                                                        -- DROP FUNCTION IF EXISTS get_category_by_path(TEXT);
                                                                                                                                                                                                                                                                                                                        -- DROP FUNCTION IF EXISTS get_category_descendants(UUID);
                                                                                                                                                                                                                                                                                                                        -- DROP FUNCTION IF EXISTS refresh_category_paths();
                                                                                                                                                                                                                                                                                                                        --
                                                                                                                                                                                                                                                                                                                        -- ALTER TABLE categories DROP CONSTRAINT IF EXISTS chk_categories_parent_not_self;
                                                                                                                                                                                                                                                                                                                        --
                                                                                                                                                                                                                                                                                                                        -- DROP INDEX IF EXISTS idx_categories_parent_id;
                                                                                                                                                                                                                                                                                                                        -- DROP INDEX IF EXISTS idx_categories_nivel;
                                                                                                                                                                                                                                                                                                                        -- DROP INDEX IF EXISTS idx_categories_path;
                                                                                                                                                                                                                                                                                                                        -- DROP INDEX IF EXISTS idx_categories_ct_key;
                                                                                                                                                                                                                                                                                                                        -- DROP INDEX IF EXISTS idx_categories_activo_parent_orden;
                                                                                                                                                                                                                                                                                                                        -- DROP INDEX IF EXISTS idx_categories_root_slug_unique;
                                                                                                                                                                                                                                                                                                                        -- DROP INDEX IF EXISTS idx_categories_parent_slug_unique;
                                                                                                                                                                                                                                                                                                                        --
                                                                                                                                                                                                                                                                                                                        -- ALTER TABLE categories DROP COLUMN IF EXISTS ct_parent_key;
                                                                                                                                                                                                                                                                                                                        -- ALTER TABLE categories DROP COLUMN IF EXISTS ct_key;
                                                                                                                                                                                                                                                                                                                        -- ALTER TABLE categories DROP COLUMN IF EXISTS path;
                                                                                                                                                                                                                                                                                                                        -- ALTER TABLE categories DROP COLUMN IF EXISTS nivel;
                                                                                                                                                                                                                                                                                                                        -- ALTER TABLE categories DROP COLUMN IF EXISTS parent_id;
                                                                                                                                                                                                                                                                                                                        --
                                                                                                                                                                                                                                                                                                                        -- COMMIT;
                                                                                                                                                                                                                                                                                                                        